
apiVersion: v2
name: config-api
version: 1.13.0
kubeVersion: ">=v1.23.0-0"
description: Jans Config Api endpoints can be used to configure jans-auth-server, which is an open-source OpenID Connect Provider (OP) and UMA Authorization Server (AS)
type: application
keywords:
  - configuration
  - API
home: https://docs.gluu.org
sources:
  - https://github.com/JanssenProject/jans/jans-config-api
  - https://github.com/JanssenProject/jans/docker-jans-config-api
  - https://github.com/GluuFederation/flex/tree/main/charts/gluu/charts/config-api
maintainers:
  - name: Mohammad Abudayyeh
    email: team@gluu.org
    url: https://github.com/moabu
icon: https://gluu.org/docs/gluu-server/favicon.ico
appVersion: "1.13.0"
