
apiVersion: v2
name: config-api
version: 5.0.12
kubeVersion: ">=v1.21.0-0"
description: Jans Config Api endpoints can be used to configure jans-auth-server, which is an open-source OpenID Connect Provider (OP) and UMA Authorization Server (AS)
type: application
keywords:
  - configuration
  - API
home: https://gluu.org/docs/gluu-server
sources:
  - https://github.com/JanssenProject/jans/jans-config-api
  - https://github.com/JanssenProject/jans/docker-jans-config-api
  - https://github.com/GluuFederation/flex/tree/main/flex-cn-setup/pygluu/kubernetes/templates/helm/gluu/charts/config-api
maintainers:
  - name: Mohammad Abudayyeh
    email: support@gluu.org
    url: https://github.com/moabu
icon: https://gluu.org/docs/gluu-server/favicon.ico
appVersion: "5.0.0"
