apiVersion: v1
entries:
  gluu:
  - annotations:
      artifacthub.io/changes: |
        - Update always
      artifacthub.io/containsSecurityUpdates: "true"
      artifacthub.io/images: |
        - name: auth-server
          image: janssenproject/auth-server:1.0.0-beta.16
        - name: auth-server-key-rotation
          image: janssenproject/certmanager:1.0.0-beta.16
        - name:  client-api
          image: janssenproject/client-api:1.0.0-beta.16
        - name: configuration-manager
          image: janssenproject/configurator:1.0.0-beta.16
        - name:  config-api
          image: janssenproject/config-api:1.0.0-beta.16
        - name: fido2
          image: janssenproject/fido2:1.0.0-beta.16
        - name: opendj
          image: gluufederation/opendj:5.0.0_dev
        - name: persistence
          image: janssenproject/persistence-loader:1.0.0-beta.16
        - name: scim
          image: janssenproject/scim:1.0.0-beta.16
      artifacthub.io/license: Apache-2.0
      artifacthub.io/prerelease: "true"
      catalog.cattle.io/certified: partner
      catalog.cattle.io/display-name: Gluu Cloud Identity and Access Management
      catalog.cattle.io/release-name: gluu
    apiVersion: v2
    appVersion: 5.0.0
    created: "2022-03-14T10:30:04.4075976Z"
    dependencies:
    - condition: global.config.enabled
      name: config
      repository: ""
      version: 5.0.3
    - condition: global.config-api.enabled
      name: config-api
      repository: ""
      version: 5.0.3
    - condition: global.opendj.enabled
      name: opendj
      repository: ""
      version: 5.0.3
    - condition: global.auth-server.enabled
      name: auth-server
      repository: ""
      version: 5.0.3
    - condition: global.admin-ui.enabled
      name: admin-ui
      repository: ""
      version: 5.0.3
    - condition: global.fido2.enabled
      name: fido2
      repository: ""
      version: 5.0.3
    - condition: global.scim.enabled
      name: scim
      repository: ""
      version: 5.0.3
    - condition: global.nginx-ingress.enabled
      name: nginx-ingress
      repository: ""
      version: 5.0.3
    - condition: global.oxshibboleth.enabled
      name: oxshibboleth
      repository: ""
      version: 5.0.3
    - condition: global.oxpassport.enabled
      name: oxpassport
      repository: ""
      version: 5.0.3
    - condition: global.casa.enabled
      name: casa
      repository: ""
      version: 5.0.3
    - condition: global.auth-server-key-rotation.enabled
      name: auth-server-key-rotation
      repository: ""
      version: 5.0.3
    - condition: global.client-api.enabled
      name: client-api
      repository: ""
      version: 5.0.3
    - condition: global.persistence.enabled
      name: persistence
      repository: ""
      version: 5.0.3
    - condition: global.istio.ingress
      name: cn-istio-ingress
      repository: ""
      version: 5.0.3
    description: Gluu Access and Identity Management
    digest: a822a477c5244394cd8b4a7fc1c0e10d9a8341da5d5208dd813e14af65b0ebc8
    home: https://www.gluu.org
    icon: https://gluu.org/docs/gluu-server/favicon.ico
    kubeVersion: '>=v1.21.0-0'
    maintainers:
    - email: support@gluu.org
      name: moabu
    name: gluu
    sources:
    - https://gluu.org/docs/gluu-server
    - https://github.com/GluuFederation/flex/flex-cn-setup
    urls:
    - gluu-5.0.3.tgz
    version: 5.0.3
  - annotations:
      artifacthub.io/changes: |
        - Gluu 5.0 Openbanking Distribution. Auth-server and config-api.
        - Updated new images
        - https://gluu.org/docs/openbanking
      artifacthub.io/containsSecurityUpdates: "true"
      artifacthub.io/images: |
        - name: auth-server
          image: janssenproject/auth-server:1.0.0-beta.14
        - name: auth-server-key-rotation
          image: janssenproject/certmanager:1.0.0-beta.14
        - name:  client-api
          image: janssenproject/client-api:1.0.0-beta.14
        - name: configuration-manager
          image: janssenproject/configurator:1.0.0-beta.14
        - name:  config-api
          image: janssenproject/config-api:1.0.0-beta.14
        - name: fido2
          image: janssenproject/fido2:1.0.0-beta.14
        - name: opendj
          image: gluufederation/opendj:5.0.0_dev
        - name: persistence
          image: janssenproject/persistence-loader:1.0.0-beta.14
        - name: scim
          image: janssenproject/scim:1.0.0-beta.14
      artifacthub.io/license: Apache-2.0
      artifacthub.io/prerelease: "true"
      catalog.cattle.io/certified: partner
      catalog.cattle.io/display-name: Gluu Cloud Identity and Access Management
      catalog.cattle.io/release-name: gluu
    apiVersion: v2
    appVersion: 5.0.0
    created: "2022-03-14T10:30:04.373598Z"
    dependencies:
    - condition: global.config.enabled
      name: config
      repository: ""
      version: 5.0.2
    - condition: global.config-api.enabled
      name: config-api
      repository: ""
      version: 5.0.2
    - condition: global.opendj.enabled
      name: opendj
      repository: ""
      version: 5.0.2
    - condition: global.jackrabbit.enabled
      name: jackrabbit
      repository: ""
      version: 5.0.2
    - condition: global.auth-server.enabled
      name: auth-server
      repository: ""
      version: 5.0.2
    - condition: global.admin-ui.enabled
      name: admin-ui
      repository: ""
      version: 5.0.2
    - condition: global.fido2.enabled
      name: fido2
      repository: ""
      version: 5.0.2
    - condition: global.scim.enabled
      name: scim
      repository: ""
      version: 5.0.2
    - condition: global.nginx-ingress.enabled
      name: nginx-ingress
      repository: ""
      version: 5.0.2
    - condition: global.oxshibboleth.enabled
      name: oxshibboleth
      repository: ""
      version: 5.0.2
    - condition: config.configmap.cnPassportEnabled
      name: oxpassport
      repository: ""
      version: 5.0.2
    - condition: config.configmap.cnCasaEnabled
      name: casa
      repository: ""
      version: 5.0.2
    - condition: global.auth-server-key-rotation.enabled
      name: auth-server-key-rotation
      repository: ""
      version: 5.0.2
    - condition: global.cr-rotate.enabled
      name: cr-rotate
      repository: ""
      version: 5.0.2
    - condition: global.client-api.enabled
      name: client-api
      repository: ""
      version: 5.0.2
    - condition: global.persistence.enabled
      name: persistence
      repository: ""
      version: 5.0.2
    - condition: global.istio.ingress
      name: cn-istio-ingress
      repository: ""
      version: 5.0.2
    description: Gluu Access and Identity Management OpenBanking distribution
    digest: 530c409476ecef759bc0ef70ef2b99cbc478cec2659979c17042ae112d5aadf6
    home: https://www.gluu.org
    icon: https://gluu.org/docs/gluu-server/favicon.ico
    kubeVersion: '>=v1.21.0-0'
    maintainers:
    - email: support@gluu.org
      name: moabu
    name: gluu
    sources:
    - https://gluu.org/docs/gluu-server
    - https://github.com/GluuFederation/cloud-native-edition
    urls:
    - gluu-5.0.2.tgz
    version: 5.0.2
  - annotations:
      artifacthub.io/changes: |
        - Gluu 5.0 Openbanking Distribution. Auth-server and config-api.
        - Updated new images
        - https://gluu.org/docs/openbanking
      artifacthub.io/containsSecurityUpdates: "true"
      artifacthub.io/images: |
        - name: auth-server
          image: janssenproject/auth-server:1.0.0-beta.13
        - name: auth-server-key-rotation
          image: janssenproject/certmanager:1.0.0-beta.13
        - name:  client-api
          image: janssenproject/client-api:1.0.0-beta.13
        - name: configuration-manager
          image: janssenproject/configurator:1.0.0-beta.13
        - name:  config-api
          image: janssenproject/config-api:1.0.0-beta.13
        - name: fido2
          image: janssenproject/fido2:1.0.0-beta.13
        - name: opendj
          image: gluufederation/opendj:5.0.0_dev
        - name: persistence
          image: janssenproject/persistence-loader:1.0.0-beta.13
        - name: scim
          image: janssenproject/scim:1.0.0-beta.13
      artifacthub.io/license: Apache-2.0
      artifacthub.io/prerelease: "true"
      catalog.cattle.io/certified: partner
      catalog.cattle.io/display-name: Gluu Cloud Identity and Access Management
      catalog.cattle.io/release-name: gluu
    apiVersion: v2
    appVersion: 5.0.0
    created: "2022-03-14T10:30:04.3496292Z"
    dependencies:
    - condition: global.config.enabled
      name: config
      repository: ""
      version: 5.0.1
    - condition: global.config-api.enabled
      name: config-api
      repository: ""
      version: 5.0.1
    - condition: global.opendj.enabled
      name: opendj
      repository: ""
      version: 5.0.1
    - condition: global.jackrabbit.enabled
      name: jackrabbit
      repository: ""
      version: 5.0.1
    - condition: global.auth-server.enabled
      name: auth-server
      repository: ""
      version: 5.0.1
    - condition: global.admin-ui.enabled
      name: admin-ui
      repository: ""
      version: 5.0.1
    - condition: global.fido2.enabled
      name: fido2
      repository: ""
      version: 5.0.1
    - condition: global.scim.enabled
      name: scim
      repository: ""
      version: 5.0.1
    - condition: global.nginx-ingress.enabled
      name: nginx-ingress
      repository: ""
      version: 5.0.1
    - condition: global.oxshibboleth.enabled
      name: oxshibboleth
      repository: ""
      version: 5.0.1
    - condition: config.configmap.cnPassportEnabled
      name: oxpassport
      repository: ""
      version: 5.0.1
    - condition: config.configmap.cnCasaEnabled
      name: casa
      repository: ""
      version: 5.0.1
    - condition: global.auth-server-key-rotation.enabled
      name: auth-server-key-rotation
      repository: ""
      version: 5.0.1
    - condition: global.cr-rotate.enabled
      name: cr-rotate
      repository: ""
      version: 5.0.1
    - condition: global.client-api.enabled
      name: client-api
      repository: ""
      version: 5.0.1
    - condition: global.persistence.enabled
      name: persistence
      repository: ""
      version: 5.0.1
    - condition: global.istio.ingress
      name: cn-istio-ingress
      repository: ""
      version: 5.0.1
    description: Gluu Access and Identity Management OpenBanking distribution
    digest: 6057aad81e905c4e1f0cca0c77b1a9d1bb952eb0f766eb5bc83d4a0ff2c54156
    home: https://www.gluu.org
    icon: https://gluu.org/docs/gluu-server/favicon.ico
    kubeVersion: '>=v1.21.0-0'
    maintainers:
    - email: support@gluu.org
      name: moabu
    name: gluu
    sources:
    - https://gluu.org/docs/gluu-server
    - https://github.com/GluuFederation/cloud-native-edition
    urls:
    - gluu-5.0.1.tgz
    version: 5.0.1
  - annotations:
      artifacthub.io/changes: |
        - Gluu 5.0 Openbanking Distribution. Auth-server and config-api.
        - Updated new images
        - https://gluu.org/docs/openbanking
      artifacthub.io/containsSecurityUpdates: "true"
      artifacthub.io/images: |
        - name: auth-server
          image: janssenproject/auth-server:1.0.0_b12
        - name: auth-server-key-rotation
          image: janssenproject/certmanager:1.0.0_b12
        - name:  client-api
          image: janssenproject/client-api:1.0.0_b12
        - name: configuration-manager
          image: janssenproject/configurator:1.0.0_b12
        - name:  config-api
          image: janssenproject/config-api:1.0.0_b12
        - name: fido2
          image: janssenproject/fido2:1.0.0_b12
        - name: opendj
          image: gluufederation/opendj:5.0.0_dev
        - name: persistence
          image: janssenproject/persistence-loader:1.0.0_b12
        - name: scim
          image: janssenproject/scim:1.0.0_b12
      artifacthub.io/license: Apache-2.0
      artifacthub.io/prerelease: "true"
      catalog.cattle.io/certified: partner
      catalog.cattle.io/display-name: Gluu Cloud Identity and Access Management
      catalog.cattle.io/release-name: gluu
    apiVersion: v2
    appVersion: 5.0.0
    created: "2022-03-14T10:30:04.3256206Z"
    dependencies:
    - condition: global.config.enabled
      name: config
      repository: ""
      version: 5.0.0
    - condition: global.config-api.enabled
      name: config-api
      repository: ""
      version: 5.0.0
    - condition: global.opendj.enabled
      name: opendj
      repository: ""
      version: 5.0.0
    - condition: global.jackrabbit.enabled
      name: jackrabbit
      repository: ""
      version: 5.0.0
    - condition: global.auth-server.enabled
      name: auth-server
      repository: ""
      version: 5.0.0
    - condition: global.fido2.enabled
      name: fido2
      repository: ""
      version: 5.0.0
    - condition: global.scim.enabled
      name: scim
      repository: ""
      version: 5.0.0
    - condition: global.nginx-ingress.enabled
      name: nginx-ingress
      repository: ""
      version: 5.0.0
    - condition: global.oxshibboleth.enabled
      name: oxshibboleth
      repository: ""
      version: 5.0.0
    - condition: config.configmap.cnPassportEnabled
      name: oxpassport
      repository: ""
      version: 5.0.0
    - condition: config.configmap.cnCasaEnabled
      name: casa
      repository: ""
      version: 5.0.0
    - condition: global.auth-server-key-rotation.enabled
      name: auth-server-key-rotation
      repository: ""
      version: 5.0.0
    - condition: global.cr-rotate.enabled
      name: cr-rotate
      repository: ""
      version: 5.0.0
    - condition: global.client-api.enabled
      name: client-api
      repository: ""
      version: 5.0.0
    - condition: global.persistence.enabled
      name: persistence
      repository: ""
      version: 5.0.0
    - condition: global.istio.ingress
      name: cn-istio-ingress
      repository: ""
      version: 5.0.0
    description: Gluu Access and Identity Management OpenBanking distribution
    digest: 2ffb3a6942077309efc36422a772de185c6f52dea9fb58cfc511b8ee52873b55
    home: https://www.gluu.org
    icon: https://gluu.org/docs/gluu-server/favicon.ico
    kubeVersion: '>=v1.19.0-0'
    maintainers:
    - email: support@gluu.org
      name: moabu
    name: gluu
    sources:
    - https://gluu.org/docs/gluu-server
    - https://github.com/GluuFederation/cloud-native-edition
    urls:
    - gluu-5.0.0.tgz
    version: 5.0.0
generated: "2022-03-14T10:30:04.2986375Z"
