
apiVersion: v2
name: config
version: 5.0.4
kubeVersion: ">=v1.21.0-0"
description: Configuration parameters for setup and initial configuration secret and config layers used by Gluu services.
type: application
keywords:
  - configuration
  - secrets
home: https://gluu.org/docs/gluu-server/reference/container-configs/
sources:
  - https://gluu.org/docs/gluu-server/reference/container-configs/
  - https://github.com/JanssenProject/jans/docker-jans-configurator
  - https://github.com/GluuFederation/flex/tree/main/flex-cn-setup/pygluu/kubernetes/templates/helm/gluu/charts/config
maintainers:
  - name: Mohammad Abudayyeh
    email: support@gluu.org
    url: https://github.com/moabu
icon: https://gluu.org/docs/gluu-server/favicon.ico
appVersion: "5.0.0"
