
apiVersion: v2
name: persistence
version: 5.16.0
kubeVersion: ">=v1.21.0-0"
description: Job to generate data and initial config for Gluu Server persistence layer.
type: application
keywords:
  - persistence prep
home: https://docs.gluu.org
sources:
  - https://github.com/JanssenProject/jans/docker-jans-persistence-loader
  - https://github.com/GluuFederation/flex/tree/main/charts/gluu/charts/persistence
maintainers:
  - name: Mohammad Abudayyeh
    email: team@gluu.org
    url: https://github.com/moabu
icon: https://gluu.org/docs/gluu-server/favicon.ico
appVersion: "5.16.0"

