
apiVersion: v2
name:  cn-istio-ingress
version: 5.0.6
kubeVersion: ">=v1.21.0-0"
description: Istio Gateway
type: application
keywords:
  - istio
  - gateway
home: https://gluu.org/docs/gluu-server/
sources:
  - https://gluu.org/docs/gluu-server/
  - https://github.com/GluuFederation/flex/tree/main/flex-cn-setup/pygluu/kubernetes/templates/helm/gluu/charts/cn-istio-ingress
maintainers:
  - name: Mohammad Abudayyeh
    email: support@gluu.org
    url: https://github.com/moabu
icon: https://gluu.org/docs/gluu-server/favicon.ico
appVersion: "5.0.0"
