kubeVersion: ">=v1.23.0-0"
annotations:
  artifacthub.io/containsSecurityUpdates: 'true'
  artifacthub.io/images: |
    - name: all-in-one
      image: ghcr.io/gluufederation/flex/flex-all-in-one:5.15.0-1
  artifacthub.io/license: Apache-2.0
  catalog.cattle.io/certified: partner
  catalog.cattle.io/release-name: gluu-all-in-one
  catalog.cattle.io/display-name: Gluu Flex Cloud Identity and Access Management All-in-One
apiVersion: v2
appVersion: "5.15.0"
icon: >-
  https://gluu.org/docs/gluu-server/favicon.ico
home: https://docs.gluu.org
sources:
  - https://docs.gluu.org
  - https://github.com/GluuProject/jans/charts/janssen
maintainers:
  - name: moabu
    email: team@gluu.org
description: Gluu Access and Identity Management All-in-One Chart. This chart deploys the selected janssen microservice all in one deployment.
name: gluu-all-in-one
version: 5.15.0
