
apiVersion: v2
name: opendj
version: 5.1.2
kubeVersion: ">=v1.21.0-0"
description: OpenDJ is a directory server which implements a wide range of Lightweight Directory Access Protocol and related standards, including full compliance with LDAPv3 but also support for Directory Service Markup Language (DSMLv2).Written in Java, OpenDJ offers multi-master replication, access control, and many extensions.
type: application
keywords:
  - LDAP
  - OpenDJ
home: https://docs.gluu.org
sources:
  - https://github.com/GluuFederation/docker-opendj
  - https://github.com/GluuFederation/flex/tree/main/charts/gluu/charts/opendj
maintainers:
  - name: Mohammad Abudayyeh
    email: team@gluu.org
    url: https://github.com/moabu
icon: https://gluu.org/docs/gluu-server/favicon.ico
appVersion: "5.1.2"