# Project information
site_name: Gluu Flex 1.0 Docs
site_description: Documentation for Gluu Flex

# Copyright
copyright: Copyright &copy; 2022, Gluu, Inc.

# Repository
docs_dir: source
repo_name: GluuFederation/flex
repo_url: https://github.com/GluuFederation/flex/
edit_uri: edit/4.3/docs/source

# Configuration
theme:
    name: material
    custom_dir: 'theme'
    palette:
        primary: 'green'
        accent: 'green'
    logo: 'gluu.jpg'
    favicon: 'favicon.ico'
extra:
    version: '1.0'
extra_css:
  - css/tabs.css

# Tracking
google_analytics:
  - 'UA-31008645-7'
  - 'auto'

# Extensions
markdown_extensions:
- admonition
- attr_list
- toc:
     permalink: '#'
- codehilite
- pymdownx.superfences
- pymdownx.tabbed

# Navigation
nav:

