
apiVersion: v2
name: auth-server
version: 5.0.10
kubeVersion: ">=v1.21.0-0"
description: OAuth Authorization Server, the OpenID Connect Provider, the UMA Authorization Server--this is the main Internet facing component of Gluu. It's the service that returns tokens, JWT's and identity assertions. This service must be Internet facing.
type: application
keywords:
  - Autherization
  - OpenID
home: https://gluu.org/docs/gluu-server
sources:
  - https://github.com/JanssenProject/jans-auth-server
  - https://github.com/JanssenProject/docker-jans-auth-server
  - https://github.com/GluuFederation/flex/tree/main/flex-cn-setup/pygluu/kubernetes/templates/helm/gluu/charts/auth-server
maintainers:
  - name: Mohammad Abudayyeh
    email: support@gluu.org
    url: https://github.com/moabu
icon: https://gluu.org/docs/gluu-server/favicon.ico
appVersion: 5.0.0
